### ISSUE TITLE
Pip install fails in conda env

### ISSUE THREAD

**Issue by benjamin9555** [bluebird75/winpdb#25]
OS: 16.04.6
python version: 3.7.3
pip version: 19.1
conda version: 4.6.14

```
└─▪ pip install winpdb-reborn
Collecting winpdb-reborn
  Using cached https://files.pythonhosted.org/packages/8f/f9/b25cde38dd15c590f4d4a1f3f5eb3614167deea1ee9449779347f400ed40/winpdb_reborn-2.0.0.dev5-py3-none-any.whl
Collecting wxpython>=4 (from winpdb-reborn)
  Using cached https://files.pythonhosted.org/packages/9a/a1/9c081e04798eb134b63def3db121a6e4436e1d84e76692503deef8e75423/wxPython-4.0.6.tar.gz
Requirement already satisfied: numpy in /groups/funke/home/gallusserb/miniconda3/envs/pyg_test/lib/python3.7/site-packages (from wxpython>=4->winpdb-reborn) (1.16.3)
Requirement already satisfied: pillow in /groups/funke/home/gallusserb/miniconda3/envs/pyg_test/lib/python3.7/site-packages (from wxpython>=4->winpdb-reborn) (6.0.0)
Requirement already satisfied: six in /groups/funke/home/gallusserb/miniconda3/envs/pyg_test/lib/python3.7/site-packages (from wxpython>=4->winpdb-reborn) (1.12.0)
Building wheels for collected packages: wxpython
  Building wheel for wxpython (setup.py) ... error
  ERROR: Complete output from command /groups/funke/home/gallusserb/miniconda3/envs/pyg_test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-wh396n1v/wxpython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-41g_588s --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.

  "/groups/funke/home/gallusserb/miniconda3/envs/pyg_test/bin/python" -u build.py build
  Traceback (most recent call last):
    File "build.py", line 30, in <module>
      import pathlib2
  ModuleNotFoundError: No module named 'pathlib2'
  Command '"/groups/funke/home/gallusserb/miniconda3/envs/pyg_test/bin/python" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxpython
 Running setup.py clean for wxpython
Failed to build wxpython
Installing collected packages: wxpython, winpdb-reborn
  Running setup.py install for wxpython ... error
    ERROR: Complete output from command /groups/funke/home/gallusserb/miniconda3/envs/pyg_test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-wh396n1v/wxpython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gujop72s/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "/groups/funke/home/gallusserb/miniconda3/envs/pyg_test/bin/python" -u build.py build
    Traceback (most recent call last):
      File "build.py", line 30, in <module>
        import pathlib2
    ModuleNotFoundError: No module named 'pathlib2'
    Command '"/groups/funke/home/gallusserb/miniconda3/envs/pyg_test/bin/python" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command "/groups/funke/home/gallusserb/miniconda3/envs/pyg_test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-wh396n1v/wxpython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gujop72s/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-wh396n1v/wxpython/
```

**Comment by johncolby** [comment]
I didn't dig into why the `wxpython` dependency build was failing, but I just installed the prebuilt anaconda package and that seemed to work fine.

```
conda install wxpython
```

**Comment by bluebird75** [comment]
I assume this should be fixed now with the more recent versions of WxPython. If anybody feels like checking...
